config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get "home/about" => "homes#about"
  resources :books, only: [:index, :show, :edit, :create, :destroy, :update]
  resources :users, only: [:index, :show, :edit, :update]
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  def self.guest
    find_or_create_by!(name: "guestuser", email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]


  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = User.find(current_user.id)
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(params[:id])
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end

    def correct_user
      @book = Book.find(params[:id])
      @user = @book.user
      redirect_to books_path unless @user == current_user
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]

  def index
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :profile_image, :introduction)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to user_path(current_user.id) unless @user == current_user
    end

    def ensure_guest_user
      user = User.find(params[:id])
      if user.name = "guestuser"
        redirect_to user_path(current_user), notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_user_info.html.erb
      <div class="col-md-3">
        <h2>User info</h2>
        <% if user.profile_image.attached? %>
          <%= image_tag user.profile_image, size: "100x100" %>
        <% else %>
          <%= image_tag "default-image.jpeg" %>
        <% end %>
          <table class="table">
            <tr></tr>
            <tr>
              <th>name</th>
              <th><%= user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= user.introduction %></th>
            </tr>
          </table>
          <% if user.name != "guestuser" %>
            <div class="row">
              <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
                <i class="fas fa-user-cog"></i>
              <% end %>
            </div>
          <% end %>
        <h2 class="mt-3">New book</h2>
          <%= form_with model: Book do |f| %>
          <div class="form-group">
              <label for="book_title">Title</label>
              <%= f.text_field :title, class: "form-control book_title" %>
            </div>
            <div class="form-group">
              <label for="book_opinion">Opinion</label>
              <%= f.text_area :body, class: "form-control book_body" %>
            </div>
            <div class="form-group">
              <%= f.submit "Create Book", class: "btn btn-success" %>
            </div>
          <% end %>
      </div>

app/views/books/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <% if @book.errors.any? && @book.errors.count == 1 %>
          <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% elsif @book.errors.any? && @book.errors.count >= 2 %>
          <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_with model: @book do |f| %>
          <div class="form-group">
              <label for="book_title">Title</label>
              <%= f.text_field :title, class: "form-control book_title" %>
            </div>
            <div class="form-group">
              <label for="book_opinion">Opinion</label>
              <%= f.text_area :body, class: "form-control book_body" %>
            </div>
            <div class="form-group">
              <%= f.submit "Update Book", class: "btn btn-success" %>
            </div>
          <% end %>
          <%= link_to "Show", book_path(@book.id) %> |
          <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <% if @book.errors.any? && @book.errors.count == 1 %>
      <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% elsif @book.errors.any? && @book.errors.count >= 2 %>
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="row">
      <%= render "user_info", user: @user %>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user_id) do %>
                  <% if book.user.profile_image.attached? %>
                    <%= image_tag book.user.profile_image, size: "80x80" %>
                  <% else %>
                    <%= image_tag "default-image.jpeg" %>
                  <% end %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <%= render "user_info", user: @user %>
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table table-hover table-inverse">
          <tr>
            <td>
              <% if @book.user.profile_image.attached? %>
                <%= image_tag @book.user.profile_image, size: "100x100" %>
              <% else %>
                <%= image_tag "default-image.jpeg" %>
              <% end %>
              <br>
              <%= link_to @book.user.name, user_path(@book.user_id) %>
            </td>
            <td><%= link_to @book.title, book_path(@book.id) %></td>
            <td><%= @book.body %></td>
            <% if @book.user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success btn-sm" %></td>
               <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-danger btn-sm" %></td>
            <% end %>
          </tr>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <h1 class="mx-auto px-3">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
        <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to "ゲストログイン（閲覧用）", users_guest_sign_in_path, class: "btn btn-secondary btn-sm btn-block mb-3", method: :post %>
          </div>
          <div class="row">
            <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3" %>
          </div>
          <div class="row">
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/0d2c9e36f9.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to root_path, class: 'navbar-brand' do %>
            <span>Bookers</span>
          <% end %>
          <%if user_signed_in? %>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                  <li class="nav-item"><i class="fas fa-home"></i></i> Home </li>
                <% end %>
                <%= link_to users_path, class: 'nav-link text-light' do %>
                  <li class="nav-item"><i class="fas fa-users"></i> Users </li>
                <% end %>
                <%= link_to books_path, class: 'nav-link text-light' do %>
                  <li class="nav-item"><i class="fas fa-book-open"></i> Books </li>
                <% end %>
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                  <li class="nav-item"><i class="fas fa-sign-out-alt"></i> Log out </li>
                <% end %>
              </ul>
            </div>
          <% else %>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <%= link_to root_path, class: 'nav-link text-light' do %>
                  <li class="nav-item"></li><i class="fas fa-home"></i> Home </li>
                <% end %>
                <%= link_to home_about_path, class: 'nav-link text-light' do %>
                  <li class="nav-item"><i class="fas fa-link"></i> About </li>
                <% end %>
                <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                  <li class="nav-item"><i class="fas fa-user-plus"></i> Sign up </li>
                <% end %>
                <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                  <li class="nav-item"><i class="fas fa-sign-in-alt"></i> Log in </li>
                <% end %>
              </ul>
            </div>
          <% end %>
        </div>
      </nav>
    </header>
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div  class="mx-auto" >
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <% if @user.errors.any? && @user.errors.count == 1 %>
          <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% elsif @user.errors.any? && @user.errors.count >= 2 %>
          <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_with model: @user do |f| %>
          <div class="form-group">
              <label for="user_name">Name</label>
              <%= f.text_field :name, class: "form-control name" %>
            </div>
            <div class="form-group">
              <label for="user_image">Image</label>
              <%= f.file_field :profile_image, accept: "image/*", class: "form-control-file user_image" %>
            </div>
            <div class="form-group">
              <label for="user_introduction">Introduction</label>
              <%= f.text_area :introduction, class: "form-control inrtroduction" %>
            </div>
            <div class="form-group">
              <%= f.submit "Update User", class: "btn btn-secondary" %>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <%= render "books/user_info", user: @user%>
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>Image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <% @users.each do |user| %>
            <tr>
              <td>
                <% if user.profile_image.attached? %>
                  <%= image_tag user.profile_image, size: "100x100" %>
                <% else %>
                  <%= image_tag "default-image.jpeg" %>
                <% end %>
              </td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %> </td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <%= render "books/user_info", user: @user %>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(@user.id) do %>
                  <% if @user.profile_image.attached? %>
                    <%= image_tag book.user.profile_image, size: "80x80" %>
                  <% else %>
                    <%= image_tag "default-image.jpeg" %>
                  <% end %>
                <% end %>
        </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</main>